// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AdvertisementWatch
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "status")]
        public AdWatchStatus Status;
        [DataMember(Name = "instead_of")]
        public uint? InsteadOf;
        [DataMember(Name = "ad_type")]
        public AdType AdType;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "modified_at")]
        public SpacetimeDB.Timestamp? ModifiedAt;

        public AdvertisementWatch(
            ulong Id,
            SpacetimeDB.Identity PlayerId,
            AdWatchStatus Status,
            uint? InsteadOf,
            AdType AdType,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? ModifiedAt
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.Status = Status;
            this.InsteadOf = InsteadOf;
            this.AdType = AdType;
            this.CreatedAt = CreatedAt;
            this.ModifiedAt = ModifiedAt;
        }

        public AdvertisementWatch()
        {
        }
    }
}
