// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CheatAttemptLog
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "reason")]
        public string Reason;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public CheatAttemptLog(
            ulong Id,
            SpacetimeDB.Identity PlayerId,
            string Reason,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.Reason = Reason;
            this.CreatedAt = CreatedAt;
        }

        public CheatAttemptLog()
        {
            this.Reason = "";
        }
    }
}
