// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConfigKey
    {
        [DataMember(Name = "value")]
        public string Value;

        public ConfigKey(string Value)
        {
            this.Value = Value;
        }

        public ConfigKey()
        {
            this.Value = "";
        }
    }
}
