// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConfigKeyValue
    {
        [DataMember(Name = "key")]
        public ConfigKey Key;
        [DataMember(Name = "value")]
        public string Value;

        public ConfigKeyValue(
            ConfigKey Key,
            string Value
        )
        {
            this.Key = Key;
            this.Value = Value;
        }

        public ConfigKeyValue()
        {
            this.Key = new();
            this.Value = "";
        }
    }
}
