// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DailyRewards
    {
        [DataMember(Name = "daily_reward_widgets_shown")]
        public System.Collections.Generic.List<DailyRewardWidget> DailyRewardWidgetsShown;
        [DataMember(Name = "show_three_points_before_last_daily_reward_widget")]
        public bool ShowThreePointsBeforeLastDailyRewardWidget;
        [DataMember(Name = "can_claim_first_daily_reward_widget")]
        public bool CanClaimFirstDailyRewardWidget;

        public DailyRewards(
            System.Collections.Generic.List<DailyRewardWidget> DailyRewardWidgetsShown,
            bool ShowThreePointsBeforeLastDailyRewardWidget,
            bool CanClaimFirstDailyRewardWidget
        )
        {
            this.DailyRewardWidgetsShown = DailyRewardWidgetsShown;
            this.ShowThreePointsBeforeLastDailyRewardWidget = ShowThreePointsBeforeLastDailyRewardWidget;
            this.CanClaimFirstDailyRewardWidget = CanClaimFirstDailyRewardWidget;
        }

        public DailyRewards()
        {
            this.DailyRewardWidgetsShown = new();
        }
    }
}
