// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DailyRewardWidget
    {
        [DataMember(Name = "day")]
        public ushort Day;
        [DataMember(Name = "gems")]
        public ushort Gems;

        public DailyRewardWidget(
            ushort Day,
            ushort Gems
        )
        {
            this.Day = Day;
            this.Gems = Gems;
        }

        public DailyRewardWidget()
        {
        }
    }
}
