// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Energy
    {
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "energy_boundary_reached_at")]
        public EnergyChange? EnergyBoundaryReachedAt;
        [DataMember(Name = "last_energy_regeneration_at")]
        public SpacetimeDB.Timestamp LastEnergyRegenerationAt;
        [DataMember(Name = "last_energy_calculation_at")]
        public SpacetimeDB.Timestamp LastEnergyCalculationAt;
        [DataMember(Name = "energy")]
        public byte Energy;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public Energy(
            SpacetimeDB.Identity PlayerId,
            EnergyChange? EnergyBoundaryReachedAt,
            SpacetimeDB.Timestamp LastEnergyRegenerationAt,
            SpacetimeDB.Timestamp LastEnergyCalculationAt,
            byte Energy,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.PlayerId = PlayerId;
            this.EnergyBoundaryReachedAt = EnergyBoundaryReachedAt;
            this.LastEnergyRegenerationAt = LastEnergyRegenerationAt;
            this.LastEnergyCalculationAt = LastEnergyCalculationAt;
            this.Energy = Energy;
            this.CreatedAt = CreatedAt;
        }

        public Energy()
        {
        }
    }
}
