// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnergyPanel
    {
        [DataMember(Name = "price")]
        public PricingMode Price;
        [DataMember(Name = "ad_available")]
        public bool AdAvailable;

        public EnergyPanel(
            PricingMode Price,
            bool AdAvailable
        )
        {
            this.Price = Price;
            this.AdAvailable = AdAvailable;
        }

        public EnergyPanel()
        {
            this.Price = null!;
        }
    }
}
