// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnergyWidget
    {
        [DataMember(Name = "current_energy")]
        public byte CurrentEnergy;
        [DataMember(Name = "max_energy")]
        public byte MaxEnergy;
        [DataMember(Name = "next_energy_change_at")]
        public EnergyChange? NextEnergyChangeAt;
        [DataMember(Name = "regeneration_interval_micros")]
        public long RegenerationIntervalMicros;
        [DataMember(Name = "consumption_interval_micros")]
        public long ConsumptionIntervalMicros;

        public EnergyWidget(
            byte CurrentEnergy,
            byte MaxEnergy,
            EnergyChange? NextEnergyChangeAt,
            long RegenerationIntervalMicros,
            long ConsumptionIntervalMicros
        )
        {
            this.CurrentEnergy = CurrentEnergy;
            this.MaxEnergy = MaxEnergy;
            this.NextEnergyChangeAt = NextEnergyChangeAt;
            this.RegenerationIntervalMicros = RegenerationIntervalMicros;
            this.ConsumptionIntervalMicros = ConsumptionIntervalMicros;
        }

        public EnergyWidget()
        {
        }
    }
}
