// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GemsAndCoinsPrice
    {
        [DataMember(Name = "gems")]
        public ulong Gems;
        [DataMember(Name = "coins")]
        public ulong Coins;

        public GemsAndCoinsPrice(
            ulong Gems,
            ulong Coins
        )
        {
            this.Gems = Gems;
            this.Coins = Coins;
        }

        public GemsAndCoinsPrice()
        {
        }
    }
}
