// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InAppPurchase
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "token")]
        public string Token;
        [DataMember(Name = "price")]
        public InAppPurchasePrice? Price;
        [DataMember(Name = "region_code")]
        public string? RegionCode;
        [DataMember(Name = "status")]
        public InAppPurchaseStatus Status;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "modified_at")]
        public SpacetimeDB.Timestamp? ModifiedAt;

        public InAppPurchase(
            ulong Id,
            SpacetimeDB.Identity PlayerId,
            string Token,
            InAppPurchasePrice? Price,
            string? RegionCode,
            InAppPurchaseStatus Status,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? ModifiedAt
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.Token = Token;
            this.Price = Price;
            this.RegionCode = RegionCode;
            this.Status = Status;
            this.CreatedAt = CreatedAt;
            this.ModifiedAt = ModifiedAt;
        }

        public InAppPurchase()
        {
            this.Token = "";
        }
    }
}
