// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LeaderboardEntry
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "score")]
        public ulong Score;
        [DataMember(Name = "is_public")]
        public bool IsPublic;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "modified_at")]
        public SpacetimeDB.Timestamp? ModifiedAt;

        public LeaderboardEntry(
            ulong Id,
            SpacetimeDB.Identity PlayerId,
            ulong Score,
            bool IsPublic,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? ModifiedAt
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.Score = Score;
            this.IsPublic = IsPublic;
            this.CreatedAt = CreatedAt;
            this.ModifiedAt = ModifiedAt;
        }

        public LeaderboardEntry()
        {
        }
    }
}
