// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    public enum LevelSkinVariant
    {
        NeonSectorOne,
        NeonSectorTwo,
        NeonSectorThree,
        NeonSectorFour,
        NeonSectorFive,
        LavaCoreOne,
        LavaCoreTwo,
        LavaCoreThree,
        LavaCoreFour,
        LavaCoreFive,
        FrostTunnelOne,
        FrostTunnelTwo,
        FrostTunnelThree,
        FrostTunnelFour,
        FrostTunnelFive,
        TechHiveOne,
        TechHiveTwo,
        TechHiveThree,
        TechHiveFour,
        TechHiveFive,
        SpaceRiftOne,
        SpaceRiftTwo,
        SpaceRiftThree,
        SpaceRiftFour,
        SpaceRiftFive,
    }
}
