// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LevelSkinWidgetEntry
    {
        [DataMember(Name = "variant")]
        public LevelSkinVariant Variant;
        [DataMember(Name = "status")]
        public LevelSkinWidget Status;

        public LevelSkinWidgetEntry(
            LevelSkinVariant Variant,
            LevelSkinWidget Status
        )
        {
            this.Variant = Variant;
            this.Status = Status;
        }

        public LevelSkinWidgetEntry()
        {
            this.Status = null!;
        }
    }
}
