// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MagnetWidgets
    {
        [DataMember(Name = "amount")]
        public byte Amount;
        [DataMember(Name = "range_upgrade_level")]
        public byte RangeUpgradeLevel;
        [DataMember(Name = "duration_upgrade_level")]
        public byte DurationUpgradeLevel;
        [DataMember(Name = "spawn_chance_upgrade_level")]
        public byte SpawnChanceUpgradeLevel;
        [DataMember(Name = "purchase_price")]
        public PricingMode PurchasePrice;
        [DataMember(Name = "range_upgrade_price")]
        public MagnetUpgradePrice RangeUpgradePrice;
        [DataMember(Name = "duration_upgrade_price")]
        public MagnetUpgradePrice DurationUpgradePrice;
        [DataMember(Name = "spawn_chance_upgrade_price")]
        public MagnetUpgradePrice SpawnChanceUpgradePrice;

        public MagnetWidgets(
            byte Amount,
            byte RangeUpgradeLevel,
            byte DurationUpgradeLevel,
            byte SpawnChanceUpgradeLevel,
            PricingMode PurchasePrice,
            MagnetUpgradePrice RangeUpgradePrice,
            MagnetUpgradePrice DurationUpgradePrice,
            MagnetUpgradePrice SpawnChanceUpgradePrice
        )
        {
            this.Amount = Amount;
            this.RangeUpgradeLevel = RangeUpgradeLevel;
            this.DurationUpgradeLevel = DurationUpgradeLevel;
            this.SpawnChanceUpgradeLevel = SpawnChanceUpgradeLevel;
            this.PurchasePrice = PurchasePrice;
            this.RangeUpgradePrice = RangeUpgradePrice;
            this.DurationUpgradePrice = DurationUpgradePrice;
            this.SpawnChanceUpgradePrice = SpawnChanceUpgradePrice;
        }

        public MagnetWidgets()
        {
            this.PurchasePrice = null!;
            this.RangeUpgradePrice = null!;
            this.DurationUpgradePrice = null!;
            this.SpawnChanceUpgradePrice = null!;
        }
    }
}
