// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MagnetData
    {
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "amount")]
        public byte Amount;
        [DataMember(Name = "last_purchase_day")]
        public SpacetimeDB.Timestamp LastPurchaseDay;
        [DataMember(Name = "purchased_today")]
        public byte PurchasedToday;
        [DataMember(Name = "range_upgrade_level")]
        public byte RangeUpgradeLevel;
        [DataMember(Name = "duration_upgrade_level")]
        public byte DurationUpgradeLevel;
        [DataMember(Name = "spawn_chance_upgrade_level")]
        public byte SpawnChanceUpgradeLevel;
        [DataMember(Name = "modified_at")]
        public SpacetimeDB.Timestamp? ModifiedAt;

        public MagnetData(
            SpacetimeDB.Identity PlayerId,
            byte Amount,
            SpacetimeDB.Timestamp LastPurchaseDay,
            byte PurchasedToday,
            byte RangeUpgradeLevel,
            byte DurationUpgradeLevel,
            byte SpawnChanceUpgradeLevel,
            SpacetimeDB.Timestamp? ModifiedAt
        )
        {
            this.PlayerId = PlayerId;
            this.Amount = Amount;
            this.LastPurchaseDay = LastPurchaseDay;
            this.PurchasedToday = PurchasedToday;
            this.RangeUpgradeLevel = RangeUpgradeLevel;
            this.DurationUpgradeLevel = DurationUpgradeLevel;
            this.SpawnChanceUpgradeLevel = SpawnChanceUpgradeLevel;
            this.ModifiedAt = ModifiedAt;
        }

        public MagnetData()
        {
        }
    }
}
