// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PauseEntry
    {
        [DataMember(Name = "begin")]
        public SpacetimeDB.Timestamp Begin;
        [DataMember(Name = "end")]
        public SpacetimeDB.Timestamp? End;
        [DataMember(Name = "reason")]
        public PauseReason Reason;

        public PauseEntry(
            SpacetimeDB.Timestamp Begin,
            SpacetimeDB.Timestamp? End,
            PauseReason Reason
        )
        {
            this.Begin = Begin;
            this.End = End;
            this.Reason = Reason;
        }

        public PauseEntry()
        {
        }
    }
}
