// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerMovementTrailWidgetEntry
    {
        [DataMember(Name = "variant")]
        public PlayerMovementTrailVariant Variant;
        [DataMember(Name = "status")]
        public PlayerMovementTrailWidget Status;

        public PlayerMovementTrailWidgetEntry(
            PlayerMovementTrailVariant Variant,
            PlayerMovementTrailWidget Status
        )
        {
            this.Variant = Variant;
            this.Status = Status;
        }

        public PlayerMovementTrailWidgetEntry()
        {
            this.Status = null!;
        }
    }
}
