// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerSkinWidgetEntry
    {
        [DataMember(Name = "variant")]
        public PlayerSkinVariant Variant;
        [DataMember(Name = "status")]
        public PlayerSkinWidget Status;

        public PlayerSkinWidgetEntry(
            PlayerSkinVariant Variant,
            PlayerSkinWidget Status
        )
        {
            this.Variant = Variant;
            this.Status = Status;
        }

        public PlayerSkinWidgetEntry()
        {
            this.Status = null!;
        }
    }
}
