// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "id")]
        public SpacetimeDB.Identity Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "is_banned")]
        public string? IsBanned;
        [DataMember(Name = "last_playthrough_id")]
        public ulong? LastPlaythroughId;
        [DataMember(Name = "next_get_gems_ad_watch_available_at")]
        public SpacetimeDB.Timestamp NextGetGemsAdWatchAvailableAt;
        [DataMember(Name = "last_daily_reward_claimed_at")]
        public SpacetimeDB.Timestamp? LastDailyRewardClaimedAt;
        [DataMember(Name = "number_of_claimed_daily_rewards")]
        public ushort NumberOfClaimedDailyRewards;
        [DataMember(Name = "time_difference_from_utc_in_minutes")]
        public short TimeDifferenceFromUtcInMinutes;
        [DataMember(Name = "player_skin")]
        public PlayerSkinVariant PlayerSkin;
        [DataMember(Name = "level_skin")]
        public LevelSkinVariant LevelSkin;
        [DataMember(Name = "player_movement_trail")]
        public PlayerMovementTrailVariant? PlayerMovementTrail;
        [DataMember(Name = "level")]
        public uint Level;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "modified_at")]
        public SpacetimeDB.Timestamp? ModifiedAt;

        public Player(
            SpacetimeDB.Identity Id,
            string Name,
            string? IsBanned,
            ulong? LastPlaythroughId,
            SpacetimeDB.Timestamp NextGetGemsAdWatchAvailableAt,
            SpacetimeDB.Timestamp? LastDailyRewardClaimedAt,
            ushort NumberOfClaimedDailyRewards,
            short TimeDifferenceFromUtcInMinutes,
            PlayerSkinVariant PlayerSkin,
            LevelSkinVariant LevelSkin,
            PlayerMovementTrailVariant? PlayerMovementTrail,
            uint Level,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? ModifiedAt
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.IsBanned = IsBanned;
            this.LastPlaythroughId = LastPlaythroughId;
            this.NextGetGemsAdWatchAvailableAt = NextGetGemsAdWatchAvailableAt;
            this.LastDailyRewardClaimedAt = LastDailyRewardClaimedAt;
            this.NumberOfClaimedDailyRewards = NumberOfClaimedDailyRewards;
            this.TimeDifferenceFromUtcInMinutes = TimeDifferenceFromUtcInMinutes;
            this.PlayerSkin = PlayerSkin;
            this.LevelSkin = LevelSkin;
            this.PlayerMovementTrail = PlayerMovementTrail;
            this.Level = Level;
            this.CreatedAt = CreatedAt;
            this.ModifiedAt = ModifiedAt;
        }

        public Player()
        {
            this.Name = "";
        }
    }
}
