// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Playthrough
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "score")]
        public ulong Score;
        [DataMember(Name = "coins")]
        public ulong Coins;
        [DataMember(Name = "gems")]
        public ulong Gems;
        [DataMember(Name = "is_high_score")]
        public bool IsHighScore;
        [DataMember(Name = "revive_count")]
        public byte ReviveCount;
        [DataMember(Name = "coins_doubled")]
        public bool CoinsDoubled;
        [DataMember(Name = "energy_purchases")]
        public byte EnergyPurchases;
        [DataMember(Name = "levels")]
        public uint Levels;
        [DataMember(Name = "pauses")]
        public System.Collections.Generic.List<PauseEntry> Pauses;
        [DataMember(Name = "end_reason")]
        public EndReason? EndReason;
        [DataMember(Name = "begin")]
        public SpacetimeDB.Timestamp Begin;
        [DataMember(Name = "end")]
        public SpacetimeDB.Timestamp? End;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "modified_at")]
        public SpacetimeDB.Timestamp? ModifiedAt;

        public Playthrough(
            ulong Id,
            SpacetimeDB.Identity PlayerId,
            ulong Score,
            ulong Coins,
            ulong Gems,
            bool IsHighScore,
            byte ReviveCount,
            bool CoinsDoubled,
            byte EnergyPurchases,
            uint Levels,
            System.Collections.Generic.List<PauseEntry> Pauses,
            EndReason? EndReason,
            SpacetimeDB.Timestamp Begin,
            SpacetimeDB.Timestamp? End,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? ModifiedAt
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.Score = Score;
            this.Coins = Coins;
            this.Gems = Gems;
            this.IsHighScore = IsHighScore;
            this.ReviveCount = ReviveCount;
            this.CoinsDoubled = CoinsDoubled;
            this.EnergyPurchases = EnergyPurchases;
            this.Levels = Levels;
            this.Pauses = Pauses;
            this.EndReason = EndReason;
            this.Begin = Begin;
            this.End = End;
            this.CreatedAt = CreatedAt;
            this.ModifiedAt = ModifiedAt;
        }

        public Playthrough()
        {
            this.Pauses = new();
        }
    }
}
