// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    public enum PlayerSkinVariant
    {
        Default,
        TitanCore,
        CrimsonReactor,
        NeonHelix,
        QuantumBloom,
        EmeraldCircuit,
        SolarOverdrive,
        InfernoTorque,
        RadialSurge,
        AuroraPulse,
        VerdantRift,
        MoltenFang,
        ObsidianMaw,
        VoidShatter,
        PlasmaCrown,
        RedDust,
        Greeno,
    }
}
