// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerMovementTrail
    {
        [DataMember(Name = "data_id")]
        public ulong DataId;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "variant")]
        public PlayerMovementTrailVariant Variant;
        [DataMember(Name = "purchased")]
        public bool Purchased;
        [DataMember(Name = "modified_at")]
        public SpacetimeDB.Timestamp? ModifiedAt;

        public PlayerMovementTrail(
            ulong DataId,
            SpacetimeDB.Identity PlayerId,
            PlayerMovementTrailVariant Variant,
            bool Purchased,
            SpacetimeDB.Timestamp? ModifiedAt
        )
        {
            this.DataId = DataId;
            this.PlayerId = PlayerId;
            this.Variant = Variant;
            this.Purchased = Purchased;
            this.ModifiedAt = ModifiedAt;
        }

        public PlayerMovementTrail()
        {
        }
    }
}
