// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Purchase
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "variant")]
        public PurchaseVariant Variant;
        [DataMember(Name = "gems")]
        public ulong Gems;
        [DataMember(Name = "coins")]
        public ulong Coins;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public Purchase(
            ulong Id,
            SpacetimeDB.Identity PlayerId,
            PurchaseVariant Variant,
            ulong Gems,
            ulong Coins,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.Variant = Variant;
            this.Gems = Gems;
            this.Coins = Coins;
            this.CreatedAt = CreatedAt;
        }

        public Purchase()
        {
            this.Variant = null!;
        }
    }
}
