// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    public partial record PurchaseVariant : SpacetimeDB.TaggedEnum<(
        SpacetimeDB.Unit Energy,
        SpacetimeDB.Unit Revive,
        SpacetimeDB.Unit Magnet,
        SpacetimeDB.Unit MagnetRangeUpgrade,
        SpacetimeDB.Unit MagnetDurationUpgrade,
        SpacetimeDB.Unit MagnetSpawnChanceUpgrade,
        SpacetimeDB.Unit Shield,
        SpacetimeDB.Unit ShieldCollisionsUpgrade,
        SpacetimeDB.Unit ShieldDurationUpgrade,
        SpacetimeDB.Unit ShieldSpawnChanceUpgrade,
        PlayerSkinVariant PlayerSkin,
        LevelSkinVariant LevelSkin,
        PlayerMovementTrailVariant PlayerMovementTrail
    )>;
}
