// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Revive
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "playthrough_id")]
        public ulong PlaythroughId;
        [DataMember(Name = "revive_type")]
        public ReviveType ReviveType;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "modified_at")]
        public SpacetimeDB.Timestamp? ModifiedAt;

        public Revive(
            ulong Id,
            SpacetimeDB.Identity PlayerId,
            ulong PlaythroughId,
            ReviveType ReviveType,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? ModifiedAt
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.PlaythroughId = PlaythroughId;
            this.ReviveType = ReviveType;
            this.CreatedAt = CreatedAt;
            this.ModifiedAt = ModifiedAt;
        }

        public Revive()
        {
            this.ReviveType = null!;
        }
    }
}
