// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShieldWidgets
    {
        [DataMember(Name = "amount")]
        public byte Amount;
        [DataMember(Name = "collisions_upgrade_level")]
        public byte CollisionsUpgradeLevel;
        [DataMember(Name = "duration_upgrade_level")]
        public byte DurationUpgradeLevel;
        [DataMember(Name = "spawn_chance_upgrade_level")]
        public byte SpawnChanceUpgradeLevel;
        [DataMember(Name = "purchase_price")]
        public PricingMode PurchasePrice;
        [DataMember(Name = "collisions_upgrade_price")]
        public ShieldUpgradePrice CollisionsUpgradePrice;
        [DataMember(Name = "duration_upgrade_price")]
        public ShieldUpgradePrice DurationUpgradePrice;
        [DataMember(Name = "spawn_chance_upgrade_price")]
        public ShieldUpgradePrice SpawnChanceUpgradePrice;

        public ShieldWidgets(
            byte Amount,
            byte CollisionsUpgradeLevel,
            byte DurationUpgradeLevel,
            byte SpawnChanceUpgradeLevel,
            PricingMode PurchasePrice,
            ShieldUpgradePrice CollisionsUpgradePrice,
            ShieldUpgradePrice DurationUpgradePrice,
            ShieldUpgradePrice SpawnChanceUpgradePrice
        )
        {
            this.Amount = Amount;
            this.CollisionsUpgradeLevel = CollisionsUpgradeLevel;
            this.DurationUpgradeLevel = DurationUpgradeLevel;
            this.SpawnChanceUpgradeLevel = SpawnChanceUpgradeLevel;
            this.PurchasePrice = PurchasePrice;
            this.CollisionsUpgradePrice = CollisionsUpgradePrice;
            this.DurationUpgradePrice = DurationUpgradePrice;
            this.SpawnChanceUpgradePrice = SpawnChanceUpgradePrice;
        }

        public ShieldWidgets()
        {
            this.PurchasePrice = null!;
            this.CollisionsUpgradePrice = null!;
            this.DurationUpgradePrice = null!;
            this.SpawnChanceUpgradePrice = null!;
        }
    }
}
