// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CoinWidgetHandle : RemoteTableHandle<EventContext, Coins>
        {
            protected override string RemoteTableName => "coin_widget";

            internal CoinWidgetHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly CoinWidgetHandle CoinWidget;
    }

    public sealed class CoinWidgetCols
    {
        public global::SpacetimeDB.Col<Coins, ulong> Amount { get; }

        public CoinWidgetCols(string tableName)
        {
            Amount = new global::SpacetimeDB.Col<Coins, ulong>(tableName, "amount");
        }
    }

    public sealed class CoinWidgetIxCols
    {

        public CoinWidgetIxCols(string tableName)
        {
        }
    }
}
