// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DailyRewardWidgetsHandle : RemoteTableHandle<EventContext, DailyRewards>
        {
            protected override string RemoteTableName => "daily_reward_widgets";

            internal DailyRewardWidgetsHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly DailyRewardWidgetsHandle DailyRewardWidgets;
    }

    public sealed class DailyRewardWidgetsCols
    {
        public global::SpacetimeDB.Col<DailyRewards, System.Collections.Generic.List<DailyRewardWidget>> DailyRewardWidgetsShown { get; }
        public global::SpacetimeDB.Col<DailyRewards, bool> ShowThreePointsBeforeLastDailyRewardWidget { get; }
        public global::SpacetimeDB.Col<DailyRewards, bool> CanClaimFirstDailyRewardWidget { get; }

        public DailyRewardWidgetsCols(string tableName)
        {
            DailyRewardWidgetsShown = new global::SpacetimeDB.Col<DailyRewards, System.Collections.Generic.List<DailyRewardWidget>>(tableName, "daily_reward_widgets_shown");
            ShowThreePointsBeforeLastDailyRewardWidget = new global::SpacetimeDB.Col<DailyRewards, bool>(tableName, "show_three_points_before_last_daily_reward_widget");
            CanClaimFirstDailyRewardWidget = new global::SpacetimeDB.Col<DailyRewards, bool>(tableName, "can_claim_first_daily_reward_widget");
        }
    }

    public sealed class DailyRewardWidgetsIxCols
    {

        public DailyRewardWidgetsIxCols(string tableName)
        {
        }
    }
}
