// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnergyWidgetHandle : RemoteTableHandle<EventContext, EnergyWidget>
        {
            protected override string RemoteTableName => "energy_widget";

            internal EnergyWidgetHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly EnergyWidgetHandle EnergyWidget;
    }

    public sealed class EnergyWidgetCols
    {
        public global::SpacetimeDB.Col<EnergyWidget, byte> CurrentEnergy { get; }
        public global::SpacetimeDB.Col<EnergyWidget, byte> MaxEnergy { get; }
        public global::SpacetimeDB.NullableCol<EnergyWidget, EnergyChange> NextEnergyChangeAt { get; }
        public global::SpacetimeDB.Col<EnergyWidget, long> RegenerationIntervalMicros { get; }
        public global::SpacetimeDB.Col<EnergyWidget, long> ConsumptionIntervalMicros { get; }

        public EnergyWidgetCols(string tableName)
        {
            CurrentEnergy = new global::SpacetimeDB.Col<EnergyWidget, byte>(tableName, "current_energy");
            MaxEnergy = new global::SpacetimeDB.Col<EnergyWidget, byte>(tableName, "max_energy");
            NextEnergyChangeAt = new global::SpacetimeDB.NullableCol<EnergyWidget, EnergyChange>(tableName, "next_energy_change_at");
            RegenerationIntervalMicros = new global::SpacetimeDB.Col<EnergyWidget, long>(tableName, "regeneration_interval_micros");
            ConsumptionIntervalMicros = new global::SpacetimeDB.Col<EnergyWidget, long>(tableName, "consumption_interval_micros");
        }
    }

    public sealed class EnergyWidgetIxCols
    {

        public EnergyWidgetIxCols(string tableName)
        {
        }
    }
}
