// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnergyPanelHandle : RemoteTableHandle<EventContext, EnergyPanel>
        {
            protected override string RemoteTableName => "energy_panel";

            internal EnergyPanelHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly EnergyPanelHandle EnergyPanel;
    }

    public sealed class EnergyPanelCols
    {
        public global::SpacetimeDB.Col<EnergyPanel, PricingMode> Price { get; }
        public global::SpacetimeDB.Col<EnergyPanel, bool> AdAvailable { get; }

        public EnergyPanelCols(string tableName)
        {
            Price = new global::SpacetimeDB.Col<EnergyPanel, PricingMode>(tableName, "price");
            AdAvailable = new global::SpacetimeDB.Col<EnergyPanel, bool>(tableName, "ad_available");
        }
    }

    public sealed class EnergyPanelIxCols
    {

        public EnergyPanelIxCols(string tableName)
        {
        }
    }
}
