// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GemWidgetHandle : RemoteTableHandle<EventContext, Gems>
        {
            protected override string RemoteTableName => "gem_widget";

            internal GemWidgetHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly GemWidgetHandle GemWidget;
    }

    public sealed class GemWidgetCols
    {
        public global::SpacetimeDB.Col<Gems, ulong> Amount { get; }

        public GemWidgetCols(string tableName)
        {
            Amount = new global::SpacetimeDB.Col<Gems, ulong>(tableName, "amount");
        }
    }

    public sealed class GemWidgetIxCols
    {

        public GemWidgetIxCols(string tableName)
        {
        }
    }
}
