// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LevelWidgetHandle : RemoteTableHandle<EventContext, Level>
        {
            protected override string RemoteTableName => "level_widget";

            internal LevelWidgetHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly LevelWidgetHandle LevelWidget;
    }

    public sealed class LevelWidgetCols
    {
        public global::SpacetimeDB.Col<Level, uint> Amount { get; }

        public LevelWidgetCols(string tableName)
        {
            Amount = new global::SpacetimeDB.Col<Level, uint>(tableName, "amount");
        }
    }

    public sealed class LevelWidgetIxCols
    {

        public LevelWidgetIxCols(string tableName)
        {
        }
    }
}
