// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LevelSkinWidgetsHandle : RemoteTableHandle<EventContext, LevelSkinWidgetEntry>
        {
            protected override string RemoteTableName => "level_skin_widgets";

            internal LevelSkinWidgetsHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly LevelSkinWidgetsHandle LevelSkinWidgets;
    }

    public sealed class LevelSkinWidgetsCols
    {
        public global::SpacetimeDB.Col<LevelSkinWidgetEntry, LevelSkinVariant> Variant { get; }
        public global::SpacetimeDB.Col<LevelSkinWidgetEntry, LevelSkinWidget> Status { get; }

        public LevelSkinWidgetsCols(string tableName)
        {
            Variant = new global::SpacetimeDB.Col<LevelSkinWidgetEntry, LevelSkinVariant>(tableName, "variant");
            Status = new global::SpacetimeDB.Col<LevelSkinWidgetEntry, LevelSkinWidget>(tableName, "status");
        }
    }

    public sealed class LevelSkinWidgetsIxCols
    {

        public LevelSkinWidgetsIxCols(string tableName)
        {
        }
    }
}
