// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MagnetWidgetsHandle : RemoteTableHandle<EventContext, MagnetWidgets>
        {
            protected override string RemoteTableName => "magnet_widgets";

            internal MagnetWidgetsHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly MagnetWidgetsHandle MagnetWidgets;
    }

    public sealed class MagnetWidgetsCols
    {
        public global::SpacetimeDB.Col<MagnetWidgets, byte> Amount { get; }
        public global::SpacetimeDB.Col<MagnetWidgets, byte> RangeUpgradeLevel { get; }
        public global::SpacetimeDB.Col<MagnetWidgets, byte> DurationUpgradeLevel { get; }
        public global::SpacetimeDB.Col<MagnetWidgets, byte> SpawnChanceUpgradeLevel { get; }
        public global::SpacetimeDB.Col<MagnetWidgets, PricingMode> PurchasePrice { get; }
        public global::SpacetimeDB.Col<MagnetWidgets, MagnetUpgradePrice> RangeUpgradePrice { get; }
        public global::SpacetimeDB.Col<MagnetWidgets, MagnetUpgradePrice> DurationUpgradePrice { get; }
        public global::SpacetimeDB.Col<MagnetWidgets, MagnetUpgradePrice> SpawnChanceUpgradePrice { get; }

        public MagnetWidgetsCols(string tableName)
        {
            Amount = new global::SpacetimeDB.Col<MagnetWidgets, byte>(tableName, "amount");
            RangeUpgradeLevel = new global::SpacetimeDB.Col<MagnetWidgets, byte>(tableName, "range_upgrade_level");
            DurationUpgradeLevel = new global::SpacetimeDB.Col<MagnetWidgets, byte>(tableName, "duration_upgrade_level");
            SpawnChanceUpgradeLevel = new global::SpacetimeDB.Col<MagnetWidgets, byte>(tableName, "spawn_chance_upgrade_level");
            PurchasePrice = new global::SpacetimeDB.Col<MagnetWidgets, PricingMode>(tableName, "purchase_price");
            RangeUpgradePrice = new global::SpacetimeDB.Col<MagnetWidgets, MagnetUpgradePrice>(tableName, "range_upgrade_price");
            DurationUpgradePrice = new global::SpacetimeDB.Col<MagnetWidgets, MagnetUpgradePrice>(tableName, "duration_upgrade_price");
            SpawnChanceUpgradePrice = new global::SpacetimeDB.Col<MagnetWidgets, MagnetUpgradePrice>(tableName, "spawn_chance_upgrade_price");
        }
    }

    public sealed class MagnetWidgetsIxCols
    {

        public MagnetWidgetsIxCols(string tableName)
        {
        }
    }
}
