// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerSkinWidgetsHandle : RemoteTableHandle<EventContext, PlayerSkinWidgetEntry>
        {
            protected override string RemoteTableName => "player_skin_widgets";

            internal PlayerSkinWidgetsHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly PlayerSkinWidgetsHandle PlayerSkinWidgets;
    }

    public sealed class PlayerSkinWidgetsCols
    {
        public global::SpacetimeDB.Col<PlayerSkinWidgetEntry, PlayerSkinVariant> Variant { get; }
        public global::SpacetimeDB.Col<PlayerSkinWidgetEntry, PlayerSkinWidget> Status { get; }

        public PlayerSkinWidgetsCols(string tableName)
        {
            Variant = new global::SpacetimeDB.Col<PlayerSkinWidgetEntry, PlayerSkinVariant>(tableName, "variant");
            Status = new global::SpacetimeDB.Col<PlayerSkinWidgetEntry, PlayerSkinWidget>(tableName, "status");
        }
    }

    public sealed class PlayerSkinWidgetsIxCols
    {

        public PlayerSkinWidgetsIxCols(string tableName)
        {
        }
    }
}
