// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerMovementTrailWidgetsHandle : RemoteTableHandle<EventContext, PlayerMovementTrailWidgetEntry>
        {
            protected override string RemoteTableName => "player_movement_trail_widgets";

            internal PlayerMovementTrailWidgetsHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly PlayerMovementTrailWidgetsHandle PlayerMovementTrailWidgets;
    }

    public sealed class PlayerMovementTrailWidgetsCols
    {
        public global::SpacetimeDB.Col<PlayerMovementTrailWidgetEntry, PlayerMovementTrailVariant> Variant { get; }
        public global::SpacetimeDB.Col<PlayerMovementTrailWidgetEntry, PlayerMovementTrailWidget> Status { get; }

        public PlayerMovementTrailWidgetsCols(string tableName)
        {
            Variant = new global::SpacetimeDB.Col<PlayerMovementTrailWidgetEntry, PlayerMovementTrailVariant>(tableName, "variant");
            Status = new global::SpacetimeDB.Col<PlayerMovementTrailWidgetEntry, PlayerMovementTrailWidget>(tableName, "status");
        }
    }

    public sealed class PlayerMovementTrailWidgetsIxCols
    {

        public PlayerMovementTrailWidgetsIxCols(string tableName)
        {
        }
    }
}
