// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RevivePanelHandle : RemoteTableHandle<EventContext, RevivePanel>
        {
            protected override string RemoteTableName => "revive_panel";

            internal RevivePanelHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly RevivePanelHandle RevivePanel;
    }

    public sealed class RevivePanelCols
    {
        public global::SpacetimeDB.Col<RevivePanel, PricingMode> Price { get; }
        public global::SpacetimeDB.Col<RevivePanel, bool> AdAvailable { get; }

        public RevivePanelCols(string tableName)
        {
            Price = new global::SpacetimeDB.Col<RevivePanel, PricingMode>(tableName, "price");
            AdAvailable = new global::SpacetimeDB.Col<RevivePanel, bool>(tableName, "ad_available");
        }
    }

    public sealed class RevivePanelIxCols
    {

        public RevivePanelIxCols(string tableName)
        {
        }
    }
}
