// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ShieldWidgetsHandle : RemoteTableHandle<EventContext, ShieldWidgets>
        {
            protected override string RemoteTableName => "shield_widgets";

            internal ShieldWidgetsHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly ShieldWidgetsHandle ShieldWidgets;
    }

    public sealed class ShieldWidgetsCols
    {
        public global::SpacetimeDB.Col<ShieldWidgets, byte> Amount { get; }
        public global::SpacetimeDB.Col<ShieldWidgets, byte> CollisionsUpgradeLevel { get; }
        public global::SpacetimeDB.Col<ShieldWidgets, byte> DurationUpgradeLevel { get; }
        public global::SpacetimeDB.Col<ShieldWidgets, byte> SpawnChanceUpgradeLevel { get; }
        public global::SpacetimeDB.Col<ShieldWidgets, PricingMode> PurchasePrice { get; }
        public global::SpacetimeDB.Col<ShieldWidgets, ShieldUpgradePrice> CollisionsUpgradePrice { get; }
        public global::SpacetimeDB.Col<ShieldWidgets, ShieldUpgradePrice> DurationUpgradePrice { get; }
        public global::SpacetimeDB.Col<ShieldWidgets, ShieldUpgradePrice> SpawnChanceUpgradePrice { get; }

        public ShieldWidgetsCols(string tableName)
        {
            Amount = new global::SpacetimeDB.Col<ShieldWidgets, byte>(tableName, "amount");
            CollisionsUpgradeLevel = new global::SpacetimeDB.Col<ShieldWidgets, byte>(tableName, "collisions_upgrade_level");
            DurationUpgradeLevel = new global::SpacetimeDB.Col<ShieldWidgets, byte>(tableName, "duration_upgrade_level");
            SpawnChanceUpgradeLevel = new global::SpacetimeDB.Col<ShieldWidgets, byte>(tableName, "spawn_chance_upgrade_level");
            PurchasePrice = new global::SpacetimeDB.Col<ShieldWidgets, PricingMode>(tableName, "purchase_price");
            CollisionsUpgradePrice = new global::SpacetimeDB.Col<ShieldWidgets, ShieldUpgradePrice>(tableName, "collisions_upgrade_price");
            DurationUpgradePrice = new global::SpacetimeDB.Col<ShieldWidgets, ShieldUpgradePrice>(tableName, "duration_upgrade_price");
            SpawnChanceUpgradePrice = new global::SpacetimeDB.Col<ShieldWidgets, ShieldUpgradePrice>(tableName, "spawn_chance_upgrade_price");
        }
    }

    public sealed class ShieldWidgetsIxCols
    {

        public ShieldWidgetsIxCols(string tableName)
        {
        }
    }
}
