// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ApplyCosmeticHandler(ReducerEventContext ctx, SpacetimeDB.Types.CosmeticVariant cosmetic);
        public event ApplyCosmeticHandler? OnApplyCosmetic;

        public void ApplyCosmetic(SpacetimeDB.Types.CosmeticVariant cosmetic)
        {
            conn.InternalCallReducer(new Reducer.ApplyCosmetic(cosmetic));
        }

        public bool InvokeApplyCosmetic(ReducerEventContext ctx, Reducer.ApplyCosmetic args)
        {
            if (OnApplyCosmetic == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnApplyCosmetic(
                ctx,
                args.Cosmetic
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ApplyCosmetic : Reducer, IReducerArgs
        {
            [DataMember(Name = "cosmetic")]
            public CosmeticVariant Cosmetic;

            public ApplyCosmetic(CosmeticVariant Cosmetic)
            {
                this.Cosmetic = Cosmetic;
            }

            public ApplyCosmetic()
            {
                this.Cosmetic = null!;
            }

            string IReducerArgs.ReducerName => "apply_cosmetic";
        }
    }
}
