// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BanPlayerHandler(ReducerEventContext ctx, SpacetimeDB.Identity playerId, string reason);
        public event BanPlayerHandler? OnBanPlayer;

        public void BanPlayer(SpacetimeDB.Identity playerId, string reason)
        {
            conn.InternalCallReducer(new Reducer.BanPlayer(playerId, reason));
        }

        public bool InvokeBanPlayer(ReducerEventContext ctx, Reducer.BanPlayer args)
        {
            if (OnBanPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBanPlayer(
                ctx,
                args.PlayerId,
                args.Reason
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BanPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public SpacetimeDB.Identity PlayerId;
            [DataMember(Name = "reason")]
            public string Reason;

            public BanPlayer(
                SpacetimeDB.Identity PlayerId,
                string Reason
            )
            {
                this.PlayerId = PlayerId;
                this.Reason = Reason;
            }

            public BanPlayer()
            {
                this.Reason = "";
            }

            string IReducerArgs.ReducerName => "ban_player";
        }
    }
}
