// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BeginPlaythroughHandler(ReducerEventContext ctx);
        public event BeginPlaythroughHandler? OnBeginPlaythrough;

        public void BeginPlaythrough()
        {
            conn.InternalCallReducer(new Reducer.BeginPlaythrough());
        }

        public bool InvokeBeginPlaythrough(ReducerEventContext ctx, Reducer.BeginPlaythrough args)
        {
            if (OnBeginPlaythrough == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBeginPlaythrough(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BeginPlaythrough : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "begin_playthrough";
        }
    }
}
