// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BeginAdWatchHandler(ReducerEventContext ctx, SpacetimeDB.Types.AdType adType);
        public event BeginAdWatchHandler? OnBeginAdWatch;

        public void BeginAdWatch(SpacetimeDB.Types.AdType adType)
        {
            conn.InternalCallReducer(new Reducer.BeginAdWatch(adType));
        }

        public bool InvokeBeginAdWatch(ReducerEventContext ctx, Reducer.BeginAdWatch args)
        {
            if (OnBeginAdWatch == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBeginAdWatch(
                ctx,
                args.AdType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BeginAdWatch : Reducer, IReducerArgs
        {
            [DataMember(Name = "ad_type")]
            public AdType AdType;

            public BeginAdWatch(AdType AdType)
            {
                this.AdType = AdType;
            }

            public BeginAdWatch()
            {
            }

            string IReducerArgs.ReducerName => "begin_ad_watch";
        }
    }
}
