// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimDailyRewardHandler(ReducerEventContext ctx);
        public event ClaimDailyRewardHandler? OnClaimDailyReward;

        public void ClaimDailyReward()
        {
            conn.InternalCallReducer(new Reducer.ClaimDailyReward());
        }

        public bool InvokeClaimDailyReward(ReducerEventContext ctx, Reducer.ClaimDailyReward args)
        {
            if (OnClaimDailyReward == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimDailyReward(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimDailyReward : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "claim_daily_reward";
        }
    }
}
