// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ContinuePlaythroughHandler(ReducerEventContext ctx);
        public event ContinuePlaythroughHandler? OnContinuePlaythrough;

        public void ContinuePlaythrough()
        {
            conn.InternalCallReducer(new Reducer.ContinuePlaythrough());
        }

        public bool InvokeContinuePlaythrough(ReducerEventContext ctx, Reducer.ContinuePlaythrough args)
        {
            if (OnContinuePlaythrough == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnContinuePlaythrough(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ContinuePlaythrough : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "continue_playthrough";
        }
    }
}
