// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EndAdWatchHandler(ReducerEventContext ctx, ulong adWatchId, SpacetimeDB.Types.AdWatchStatus adWatchStatus);
        public event EndAdWatchHandler? OnEndAdWatch;

        public void EndAdWatch(ulong adWatchId, SpacetimeDB.Types.AdWatchStatus adWatchStatus)
        {
            conn.InternalCallReducer(new Reducer.EndAdWatch(adWatchId, adWatchStatus));
        }

        public bool InvokeEndAdWatch(ReducerEventContext ctx, Reducer.EndAdWatch args)
        {
            if (OnEndAdWatch == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEndAdWatch(
                ctx,
                args.AdWatchId,
                args.AdWatchStatus
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EndAdWatch : Reducer, IReducerArgs
        {
            [DataMember(Name = "ad_watch_id")]
            public ulong AdWatchId;
            [DataMember(Name = "ad_watch_status")]
            public AdWatchStatus AdWatchStatus;

            public EndAdWatch(
                ulong AdWatchId,
                AdWatchStatus AdWatchStatus
            )
            {
                this.AdWatchId = AdWatchId;
                this.AdWatchStatus = AdWatchStatus;
            }

            public EndAdWatch()
            {
            }

            string IReducerArgs.ReducerName => "end_ad_watch";
        }
    }
}
