// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EndPlaythroughHandler(ReducerEventContext ctx, SpacetimeDB.Types.EndReason endReason, ulong score, ulong coins, ulong gems, bool isHighScore, uint levels);
        public event EndPlaythroughHandler? OnEndPlaythrough;

        public void EndPlaythrough(SpacetimeDB.Types.EndReason endReason, ulong score, ulong coins, ulong gems, bool isHighScore, uint levels)
        {
            conn.InternalCallReducer(new Reducer.EndPlaythrough(endReason, score, coins, gems, isHighScore, levels));
        }

        public bool InvokeEndPlaythrough(ReducerEventContext ctx, Reducer.EndPlaythrough args)
        {
            if (OnEndPlaythrough == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEndPlaythrough(
                ctx,
                args.EndReason,
                args.Score,
                args.Coins,
                args.Gems,
                args.IsHighScore,
                args.Levels
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EndPlaythrough : Reducer, IReducerArgs
        {
            [DataMember(Name = "end_reason")]
            public EndReason EndReason;
            [DataMember(Name = "score")]
            public ulong Score;
            [DataMember(Name = "coins")]
            public ulong Coins;
            [DataMember(Name = "gems")]
            public ulong Gems;
            [DataMember(Name = "is_high_score")]
            public bool IsHighScore;
            [DataMember(Name = "levels")]
            public uint Levels;

            public EndPlaythrough(
                EndReason EndReason,
                ulong Score,
                ulong Coins,
                ulong Gems,
                bool IsHighScore,
                uint Levels
            )
            {
                this.EndReason = EndReason;
                this.Score = Score;
                this.Coins = Coins;
                this.Gems = Gems;
                this.IsHighScore = IsHighScore;
                this.Levels = Levels;
            }

            public EndPlaythrough()
            {
            }

            string IReducerArgs.ReducerName => "end_playthrough";
        }
    }
}
