// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ManageConfigHandler(ReducerEventContext ctx, SpacetimeDB.Types.ConfigAction action);
        public event ManageConfigHandler? OnManageConfig;

        public void ManageConfig(SpacetimeDB.Types.ConfigAction action)
        {
            conn.InternalCallReducer(new Reducer.ManageConfig(action));
        }

        public bool InvokeManageConfig(ReducerEventContext ctx, Reducer.ManageConfig args)
        {
            if (OnManageConfig == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnManageConfig(
                ctx,
                args.Action
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ManageConfig : Reducer, IReducerArgs
        {
            [DataMember(Name = "action")]
            public ConfigAction Action;

            public ManageConfig(ConfigAction Action)
            {
                this.Action = Action;
            }

            public ManageConfig()
            {
                this.Action = null!;
            }

            string IReducerArgs.ReducerName => "manage_config";
        }
    }
}
