// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PausePlaythroughHandler(ReducerEventContext ctx, SpacetimeDB.Types.PauseReason pauseReason);
        public event PausePlaythroughHandler? OnPausePlaythrough;

        public void PausePlaythrough(SpacetimeDB.Types.PauseReason pauseReason)
        {
            conn.InternalCallReducer(new Reducer.PausePlaythrough(pauseReason));
        }

        public bool InvokePausePlaythrough(ReducerEventContext ctx, Reducer.PausePlaythrough args)
        {
            if (OnPausePlaythrough == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPausePlaythrough(
                ctx,
                args.PauseReason
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PausePlaythrough : Reducer, IReducerArgs
        {
            [DataMember(Name = "pause_reason")]
            public PauseReason PauseReason;

            public PausePlaythrough(PauseReason PauseReason)
            {
                this.PauseReason = PauseReason;
            }

            public PausePlaythrough()
            {
            }

            string IReducerArgs.ReducerName => "pause_playthrough";
        }
    }
}
