// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SyncTimeHandler(ReducerEventContext ctx, short timeDifferenceFromUtcInMinutes);
        public event SyncTimeHandler? OnSyncTime;

        public void SyncTime(short timeDifferenceFromUtcInMinutes)
        {
            conn.InternalCallReducer(new Reducer.SyncTime(timeDifferenceFromUtcInMinutes));
        }

        public bool InvokeSyncTime(ReducerEventContext ctx, Reducer.SyncTime args)
        {
            if (OnSyncTime == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSyncTime(
                ctx,
                args.TimeDifferenceFromUtcInMinutes
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SyncTime : Reducer, IReducerArgs
        {
            [DataMember(Name = "time_difference_from_utc_in_minutes")]
            public short TimeDifferenceFromUtcInMinutes;

            public SyncTime(short TimeDifferenceFromUtcInMinutes)
            {
                this.TimeDifferenceFromUtcInMinutes = TimeDifferenceFromUtcInMinutes;
            }

            public SyncTime()
            {
            }

            string IReducerArgs.ReducerName => "sync_time";
        }
    }
}
