// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UsePowerUpHandler(ReducerEventContext ctx, SpacetimeDB.Types.PowerUpType powerUpType);
        public event UsePowerUpHandler? OnUsePowerUp;

        public void UsePowerUp(SpacetimeDB.Types.PowerUpType powerUpType)
        {
            conn.InternalCallReducer(new Reducer.UsePowerUp(powerUpType));
        }

        public bool InvokeUsePowerUp(ReducerEventContext ctx, Reducer.UsePowerUp args)
        {
            if (OnUsePowerUp == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUsePowerUp(
                ctx,
                args.PowerUpType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UsePowerUp : Reducer, IReducerArgs
        {
            [DataMember(Name = "power_up_type")]
            public PowerUpType PowerUpType;

            public UsePowerUp(PowerUpType PowerUpType)
            {
                this.PowerUpType = PowerUpType;
            }

            public UsePowerUp()
            {
            }

            string IReducerArgs.ReducerName => "use_power_up";
        }
    }
}
