// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteProcedures : RemoteBase
    {
        public void HandleInAppPurchase(string purchaseToken, ProcedureCallback<SpacetimeDB.Result<SpacetimeDB.Unit, string>> callback)
        {
            // Convert the clean callback to the wrapper callback
            InternalHandleInAppPurchase(purchaseToken, (ctx, result) => {
            if (result.IsSuccess && result.Value != null)
            {
                callback(ctx, ProcedureCallbackResult<SpacetimeDB.Result<SpacetimeDB.Unit, string>>.Success(result.Value.Value));
            }
            else
            {
                callback(ctx, ProcedureCallbackResult<SpacetimeDB.Result<SpacetimeDB.Unit, string>>.Failure(result.Error!));
            }
            });
        }

        private void InternalHandleInAppPurchase(string purchaseToken, ProcedureCallback<Procedure.HandleInAppPurchase> callback)
        {
            conn.InternalCallProcedure(new Procedure.HandleInAppPurchaseArgs(purchaseToken), callback);
        }

    }

    public abstract partial class Procedure
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleInAppPurchase
        {
            [DataMember(Name = "Value")]
            public SpacetimeDB.Result<SpacetimeDB.Unit, string> Value;

            public HandleInAppPurchase(SpacetimeDB.Result<SpacetimeDB.Unit, string> Value)
            {
                this.Value = Value;
            }

            public HandleInAppPurchase()
            {
                this.Value = default!;
            }
        }
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HandleInAppPurchaseArgs : Procedure, IProcedureArgs
        {
            [DataMember(Name = "purchase_token")]
            public string PurchaseToken;

            public HandleInAppPurchaseArgs(string PurchaseToken)
            {
                this.PurchaseToken = PurchaseToken;
            }

            public HandleInAppPurchaseArgs()
            {
                this.PurchaseToken = "";
            }

            string IProcedureArgs.ProcedureName => "handle_in_app_purchase";
        }

    }
}
